# Este es el contenido que DEBE estar en tu archivo mongodb-deployment.yaml en GitHub
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: default # ¡Asegúrate de que esta línea esté presente y sea correcta!
  labels:
    app: mongodb # Asegúrate de que esta etiqueta se use para tu selector
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      # creationTimestamp: null # Esta línea puede quedarse o eliminarse
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:4.4
        imagePullPolicy: IfNotPresent
        name: mongo
        resources: {}

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30